// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APITest.Domain;

public partial class ProductSearchHistory
{
    public int Id { get; set; }

    public string SearchKey { get; set; }

    public int? SearchByUserId { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedDate { get; set; }
}